# Generated by Django 5.1.1 on 2024-10-16 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArcadiaGames', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='image',
            field=models.ImageField(default='games_images/default.png', upload_to='games_images/'),
        ),
    ]
