# Generated by Django 5.1.1 on 2024-10-16 00:28

import ArcadiaGames.models.games
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArcadiaGames', '0002_games_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='image',
            field=models.ImageField(default='games_images/default.png', upload_to=ArcadiaGames.models.games.game_image_upload_path),
        ),
    ]
